# Generated by Django 4.2.7 on 2023-12-01 16:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0006_auto_20230516_0220'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='account',
            options={'ordering': ['-date']},
        ),
        migrations.AlterModelOptions(
            name='kyc',
            options={'ordering': ['-date']},
        ),
    ]
